version: '3'

services:
  backend:
    build: ./backend
    container_name: ma_backend_container  # Custom name for the backend container
    ports:
      - "3000:3000"  # Adjust port as needed for your backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=ma_project
      - DB_USER=postgres
      - DB_PASSWORD=abc@1234
  
  frontend:
    build: ./frontend
    container_name: ma_frontend_container  # Custom name for the frontend container
    ports:
      - "5173:5173"  # Vite's default port
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend  # Ensures backend starts first
