version: '3'

services:
  backend:
    build: ./backend
    container_name: ma_backend_container
    restart: unless-stopped
    ports:
      - "3090:3090"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: ma_frontend_container
    restart: unless-stopped
    ports:
      - "3088:3088"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
