FROM node:18.20.8
WORKDIR /usr/src/app
COPY app/package*.json ./
RUN npm install
# Install ping utilities
RUN apt-get update && apt-get install -y iputils-ping
COPY app/ ./
EXPOSE 5000
CMD ["node", "server.js"]